### ISSUE TITLE
Amount of scrobbles not showing in menu

### ISSUE THREAD

**Issue by yuuusername** [KazukiGames82/Last_fm-KazukiGames82#1]
First of, great plugin, thank you!

Now the issue.
I've been having some troubles getting the amount of scrobbles to show below my username:
![image](https://github.com/KazukiGames82/Last_fm-KazukiGames82/assets/72343301/0fa61e85-6b64-448d-9f0a-40f4e903fbf5)

The desired behaviour is similar to what you have in your screenshots:
![image](https://github.com/KazukiGames82/Last_fm-KazukiGames82/assets/72343301/37d9d1ac-7ad8-4b2d-a08f-be764c54c7b5)

I've tried resetting the app to default settings and reinstalling it but the issue is still there.

Thanks!

**Comment by KazukiGames82** [comment]
This looks like a problem with `Dropdown Menu Font Size`, also could be related to `Dropdown Menu Height`.
> Font is bigger than menu height, so the second line is not visible.
> Increasing `Dropdown Menu Height` could be fix that.
![Rainmeter_PGqVRuZMc8](https://github.com/KazukiGames82/Last_fm-KazukiGames82/assets/121910047/5515d114-f9d9-4d55-b9f0-954b5fdd5e38)

**Comment by KazukiGames82** [comment]
Also, are you able to see this line?
![Rainmeter_ZghfUOb9Z5](https://github.com/KazukiGames82/Last_fm-KazukiGames82/assets/121910047/4bcceb99-dee9-4656-a30c-55bd1df821c7)

**Comment by KazukiGames82** [comment]
> Now the issue. I've been having some troubles getting the amount of scrobbles to show below my username.

This new version `v24.0619` should fix that, and thanks for that 💕
https://github.com/KazukiGames82/Last_fm-KazukiGames82/releases/tag/v24.0619

**Comment by yuuusername** [comment]
> Also, are you able to see this line?

I was able to see the line and you were right about the font size and menu height being the issues!

> This new version v24.0619 should fix that, and thanks for that 💕
https://github.com/KazukiGames82/Last_fm-KazukiGames82/releases/tag/v24.0619

 It works! Thanks for the quick fix! 💜
